# Generated by Django 2.1.3 on 2018-12-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Clothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(blank=True, max_length=35, null=True)),
                ('item_gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unisex')], max_length=3, null=True)),
                ('item_category', models.CharField(blank=True, choices=[('A', 'Sweatshirt'), ('B', 'Hoodies'), ('C', 'Jumper')], max_length=3, null=True)),
                ('item_price', models.IntegerField(blank=True, default=30, help_text='Price of product', null=True)),
                ('item_currency', models.CharField(blank=True, choices=[('A', 'EUR'), ('B', 'GPB'), ('C', 'USD')], max_length=3, null=True)),
                ('item_width', models.IntegerField(blank=True, default=52, help_text='Use width in centimeters', null=True)),
                ('item_height', models.IntegerField(blank=True, default=72, help_text='Use height in centimeters', null=True)),
                ('item_url', models.URLField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
