# Generated by Django 2.1.3 on 2018-12-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_clothes',
            name='image_main',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='product_clothes',
            name='image_secondary',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='product_clothes',
            name='image_third',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
