# Generated by Django 2.1.3 on 2018-12-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0005_product_clothes_item_asin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_clothes',
            name='item_currency',
            field=models.CharField(blank=True, choices=[('EUR', 'EUR'), ('GPB', 'GPB'), ('USD', 'USD')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='product_clothes',
            name='item_gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Unisex', 'Unisex')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='product_clothes',
            name='item_price',
            field=models.IntegerField(blank=True, default=10, help_text='Price of product', null=True),
        ),
    ]
