# Generated by Django 2.1.3 on 2018-12-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0006_auto_20181210_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_clothes',
            name='item_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price of product', max_digits=10, null=True),
        ),
    ]
