# Generated by Django 2.1.3 on 2018-12-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0007_auto_20181210_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_clothes',
            name='image_main',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product_clothes',
            name='image_secondary',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product_clothes',
            name='image_third',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product_clothes',
            name='item_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price of product even with decimals', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product_clothes',
            name='item_url',
            field=models.URLField(blank=True, help_text='To add size to link on Amazon - use Short links', max_length=150, null=True),
        ),
    ]
