# Generated by Django 2.1.3 on 2018-12-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0009_auto_20181224_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_clothes',
            name='item_asin',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='product_clothes',
            name='item_category',
            field=models.CharField(choices=[('Sweatshirt', 'Sweatshirt'), ('Hoodies', 'Hoodies'), ('Jumper', 'Jumper')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='product_clothes',
            name='item_currency',
            field=models.CharField(choices=[('EUR', 'EUR'), ('GPB', 'GPB'), ('USD', 'USD')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='product_clothes',
            name='item_gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unisex', 'Unisex')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='product_clothes',
            name='item_height',
            field=models.IntegerField(default=72, help_text='Use height in centimeters', null=True),
        ),
        migrations.AlterField(
            model_name='product_clothes',
            name='item_price',
            field=models.DecimalField(decimal_places=2, help_text='Price of product even with decimals', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product_clothes',
            name='item_title',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='product_clothes',
            name='item_url',
            field=models.URLField(help_text='To add size to link on Amazon - use Short links', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='product_clothes',
            name='item_width',
            field=models.IntegerField(default=52, help_text='Use width in centimeters', null=True),
        ),
    ]
