# Generated by Django 2.1.3 on 2018-12-24 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0010_auto_20181224_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_clothes',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
