# Generated by Django 2.1.5 on 2019-02-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0011_product_clothes_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_clothes',
            name='item_size',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
