# Generated by Django 2.1.5 on 2019-02-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0013_auto_20190225_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_clothes',
            name='item_seller',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
