# Generated by Django 2.1.5 on 2019-02-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0014_product_clothes_item_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_clothes',
            name='item_material_composition',
            field=models.CharField(blank=True, default='No information', max_length=80, null=True),
        ),
    ]
