# Generated by Django 2.1.5 on 2019-02-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0016_auto_20190226_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_clothes',
            name='item_color',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
