# Generated by Django 2.1.5 on 2019-03-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0017_product_clothes_item_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_clothes',
            name='item_continent',
            field=models.CharField(choices=[('Europe', 'Europe'), ('North America', 'North America'), ('South America', 'South America'), ('Asia', 'Asia'), ('Africa', 'Africa'), ('Australia', 'Australia'), ('Worldwide', 'Worldwide')], default='Europe', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product_clothes',
            name='item_category',
            field=models.CharField(choices=[('Sweatshirt', 'Sweatshirt'), ('Hoodies', 'Hoodies'), ('Jumper', 'Jumper'), ('Jacket', 'Jacket')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='product_clothes',
            name='item_currency',
            field=models.CharField(choices=[('EUR', 'EUR'), ('GPB', 'GPB'), ('USD', 'USD')], default='EUR', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='product_clothes',
            name='item_seller',
            field=models.CharField(default='Amazon', max_length=25, null=True),
        ),
    ]
