# Generated by Django 2.1.5 on 2019-03-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0018_auto_20190326_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_clothes',
            name='item_category',
            field=models.CharField(choices=[('Sweatshirt', 'Sweatshirt'), ('Hoodies', 'Hoodies'), ('Jumper', 'Jumper'), ('Jacket', 'Jacket'), ('Cardigan', 'Cardigan')], max_length=40, null=True),
        ),
    ]
