# Generated by Django 2.1.5 on 2019-03-29 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0019_auto_20190327_1250'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_Clothes',
            new_name='Product_Clothes_Tops',
        ),
    ]
