# Generated by Django 2.1.5 on 2019-06-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0020_auto_20190329_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_clothes_tops',
            name='item_brand',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='product_clothes_tops',
            name='item_category',
            field=models.CharField(choices=[('Sweatshirt', 'Sweatshirt'), ('Hoodies', 'Hoodies'), ('Jumper', 'Jumper'), ('Jacket', 'Jacket'), ('Cardigan', 'Cardigan'), ('Short', 'Short')], max_length=40, null=True),
        ),
    ]
