# Generated by Django 2.1.5 on 2019-06-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0023_auto_20190609_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_clothes_tops_us',
            name='item_url',
            field=models.URLField(help_text='To add size to link on Amazon - use Short links', max_length=500, null=True),
        ),
    ]
