# Generated by Django 2.1.5 on 2019-06-14 07:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyClothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(max_length=255)),
                ('item_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=40, null=True)),
                ('item_country', models.CharField(choices=[('United States', 'United States')], max_length=255, null=True)),
                ('item_category', models.CharField(choices=[('Sweatshirt', 'Sweatshirt'), ('Hoodies', 'Hoodies'), ('Jumper', 'Jumper')], max_length=40, null=True)),
                ('item_width', models.FloatField(help_text='Use width in inches', null=True)),
                ('item_height', models.FloatField(help_text='Use height in inches', null=True)),
                ('image_main', models.ImageField(blank=True, help_text='600 x 900', max_length=200, null=True, upload_to='imagesUser/')),
                ('upload_date', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('item_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
