# Generated by Django 2.1.5 on 2019-06-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190614_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='myclothes',
            name='item_checked',
            field=models.BooleanField(default=False),
        ),
    ]
