# Generated by Django 2.1.5 on 2019-06-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_myclothes_item_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myclothes',
            name='image_main',
            field=models.ImageField(blank=True, default='default image', help_text='600 x 900', max_length=200, upload_to='imagesUser/'),
        ),
    ]
