# Generated by Django 2.1.5 on 2019-06-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190620_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myclothes',
            name='image_main',
            field=models.ImageField(blank=True, default='media/imagesUser/foto_asistentka_900x900.jpg', help_text='600 x 900', max_length=200, null=True, upload_to='imagesUser/'),
        ),
    ]
