# Generated by Django 2.1.3 on 2018-11-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductHoodies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('pub_date', models.DateTimeField()),
                ('seller', models.CharField(choices=[('UK', 'Amazon.co.uk'), ('DE', 'Amazon.de'), ('US', 'Amazon.com'), ('AL', 'Aliexpress.com')], default='Amazon.co.uk', max_length=2)),
                ('item_url', models.URLField()),
                ('item_image', models.ImageField(height_field=30, upload_to='', width_field=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSweatshirts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('pub_date', models.DateTimeField()),
                ('seller', models.CharField(choices=[('UK', 'Amazon.co.uk'), ('DE', 'Amazon.de'), ('US', 'Amazon.com'), ('AL', 'Aliexpress.com')], default='Amazon.co.uk', max_length=2)),
                ('item_url', models.URLField()),
                ('item_image', models.ImageField(height_field=30, upload_to='', width_field=10)),
            ],
        ),
    ]
