# Generated by Django 2.1.3 on 2018-12-01 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductHoodies',
        ),
        migrations.DeleteModel(
            name='ProductSweatshirts',
        ),
    ]
